### ISSUE TITLE
Does not accept options

### ISSUE THREAD

**Issue by msisto** [ughitsaaron/gulp-styleguidejs#2]
When I try to pass styleguidejs options, the task dies like so:

```
...node_modules/gulp-styleguidejs/index.js:42
      throw new PluginError(PLUGIN_NAME, err);
            ^
Error: path should be string
    at File.Object.defineProperty.set (/Users/mattsisto/src/chirp-css/node_modules/gulp/node_modules/vinyl-fs/node_modules/vinyl/index.js:166:41)
    at /Users/mattsisto/src/chirp-css/node_modules/gulp-styleguidejs/index.js:37:21
    at /Users/mattsisto/src/chirp-css/node_modules/styleguidejs/lib/index.js:119:17
    at Object.exports.renderFile (/Users/mattsisto/src/chirp-css/node_modules/styleguidejs/node_modules/jade/lib/jade.js:282:12)
    at Object.exports.jade (/Users/mattsisto/src/chirp-css/node_modules/styleguidejs/node_modules/consolidate/lib/consolidate.js:166:10)
    at Object.StyleGuide.render (/Users/mattsisto/src/chirp-css/node_modules/styleguidejs/lib/index.js:117:29)
    at DestroyableTransform._transform (/Users/mattsisto/src/chirp-css/node_modules/gulp-styleguidejs/index.js:33:10)
    at DestroyableTransform.Transform._read (/Users/mattsisto/src/chirp-css/node_modules/gulp-styleguidejs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/mattsisto/src/chirp-css/node_modules/gulp-styleguidejs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/mattsisto/src/chirp-css/node_modules/gulp-styleguidejs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
```

**gulpfile.js:**
```
var styleguidejs  = require('gulp-styleguidejs');

gulp.task('docs', function() {
  gulp.src('./src/styles.css')
    .pipe(styleguidejs({
      outputFile: 'styleguide.html'
    }))
});
```

It works as expected when I remove the `outputFile` option.

**Comment by ughitsaaron** [comment]
I'll take a look at this tomorrow! Apologies for the delay.
